### PR TITLE
Rename Bitcoin to crypto

### PR DESCRIPTION
**Pull request by wslyvh**
As discussed on #12 

I think 'Crypto' would be a better term as Bitpay is flexible and accepts a wide range of cryptocurrencies. Not just Bitcoin.

### CODE REVIEW

**Comment by raphaelm** [comment]
Thanks! I merged [4a69499](https://github.com/pretix/pretix-bitpay/pull/13/commits/4a694997321b53589712e137b682c75e4f31d3d1) manually. We'll update the version as part of our release cycle.

**Comment by wslyvh** [comment]
Makes sense! Any indication of when the new version will be released? 
I'd like to plan an update on our end accordingly.

**Comment by raphaelm** [comment]
I think next week, but no promises :)

**Comment by wslyvh** [comment]
Got it. Next week would be great tho 🙏

Appreciate the quick merge already. Wasn't sure if this was still maintained. Thanks again!

**Comment by pc-coholic** [comment]
Just to add to this conversation: The moment we rolled out the new default of Crypto - of course - people took offense and wanted Bitcoin back.

So to make this equally usable for everyone, the plugin will now default to Crypto, but allow you to set your very own payment method name in the settings.

**Pull request closed without merging**
